# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class CheckErrorResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, error_text: str=None, request_id: str=None, status: str=None):
        """CheckErrorResponse - a model defined in OpenAPI

        :param error_text: The error_text of this CheckErrorResponse.
        :param request_id: The request_id of this CheckErrorResponse.
        :param status: The status of this CheckErrorResponse.
        """
        self.openapi_types = {
            'error_text': str,
            'request_id': str,
            'status': str
        }

        self.attribute_map = {
            'error_text': 'error_text',
            'request_id': 'request_id',
            'status': 'status'
        }

        self._error_text = error_text
        self._request_id = request_id
        self._status = status

    @classmethod
    def from_dict(cls, dikt: dict) -> 'CheckErrorResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The checkErrorResponse of this CheckErrorResponse.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error_text(self):
        """Gets the error_text of this CheckErrorResponse.

        If the `status` is non-zero, this explains the error encountered.

        :return: The error_text of this CheckErrorResponse.
        :rtype: str
        """
        return self._error_text

    @error_text.setter
    def error_text(self, error_text):
        """Sets the error_text of this CheckErrorResponse.

        If the `status` is non-zero, this explains the error encountered.

        :param error_text: The error_text of this CheckErrorResponse.
        :type error_text: str
        """

        self._error_text = error_text

    @property
    def request_id(self):
        """Gets the request_id of this CheckErrorResponse.

        The `request_id` that you received in the response to the Verify request and used in the Verify check request.

        :return: The request_id of this CheckErrorResponse.
        :rtype: str
        """
        return self._request_id

    @request_id.setter
    def request_id(self, request_id):
        """Sets the request_id of this CheckErrorResponse.

        The `request_id` that you received in the response to the Verify request and used in the Verify check request.

        :param request_id: The request_id of this CheckErrorResponse.
        :type request_id: str
        """

        self._request_id = request_id

    @property
    def status(self):
        """Gets the status of this CheckErrorResponse.

        Code | Text | Description -- | -- | -- 0 | Success | The request was successfully accepted by Vonage. 1 | Throttled | You are trying to send more than the maximum of 30 requests per second. 2 | Your request is incomplete and missing the mandatory parameter `$parameter` | The stated parameter is missing. 3 | Invalid value for parameter `$parameter` | Invalid value for parameter. If you see Facility not allowed in the error text, check that you are using the correct Base URL in your request. 4 | Invalid credentials were provided | The supplied API key or secret in the request is either invalid or disabled. 5 | Internal Error | An error occurred processing this request in the Cloud Communications Platform. 6 | The Vonage platform was unable to process this message for the following reason: `$reason` | The request could not be routed. 16 | The code inserted does not match the expected value | 17 | The wrong code was provided too many times | You can run Verify check on a specific `request_id` up to three times unless a new verification code is generated. If you check a request more than three times, it is set to FAILED and you cannot check it again. 

        :return: The status of this CheckErrorResponse.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this CheckErrorResponse.

        Code | Text | Description -- | -- | -- 0 | Success | The request was successfully accepted by Vonage. 1 | Throttled | You are trying to send more than the maximum of 30 requests per second. 2 | Your request is incomplete and missing the mandatory parameter `$parameter` | The stated parameter is missing. 3 | Invalid value for parameter `$parameter` | Invalid value for parameter. If you see Facility not allowed in the error text, check that you are using the correct Base URL in your request. 4 | Invalid credentials were provided | The supplied API key or secret in the request is either invalid or disabled. 5 | Internal Error | An error occurred processing this request in the Cloud Communications Platform. 6 | The Vonage platform was unable to process this message for the following reason: `$reason` | The request could not be routed. 16 | The code inserted does not match the expected value | 17 | The wrong code was provided too many times | You can run Verify check on a specific `request_id` up to three times unless a new verification code is generated. If you check a request more than three times, it is set to FAILED and you cannot check it again. 

        :param status: The status of this CheckErrorResponse.
        :type status: str
        """
        allowed_values = ["0", "1", "2", "3", "4", "5", "6", "16", "17"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status
