# coding: utf-8

from datetime import date, datetime

from typing import List, Dict, Type

from openapi_server.models.base_model import Model
from openapi_server import util


class ResponseFour(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, error: str=None, error_description: str=None):
        """ResponseFour - a model defined in OpenAPI

        :param error: The error of this ResponseFour.
        :param error_description: The error_description of this ResponseFour.
        """
        self.openapi_types = {
            'error': str,
            'error_description': str
        }

        self.attribute_map = {
            'error': 'error',
            'error_description': 'error_description'
        }

        self._error = error
        self._error_description = error_description

    @classmethod
    def from_dict(cls, dikt: dict) -> 'ResponseFour':
        """Returns the dict as a model

        :param dikt: A dict.
        :return: The ResponseFour of this ResponseFour.
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error(self):
        """Gets the error of this ResponseFour.

        multiple_mobile_accounts

        :return: The error of this ResponseFour.
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this ResponseFour.

        multiple_mobile_accounts

        :param error: The error of this ResponseFour.
        :type error: str
        """

        self._error = error

    @property
    def error_description(self):
        """Gets the error_description of this ResponseFour.

        The mobile number provided is associated with more than one DigiLocker accounts. Please login using username.

        :return: The error_description of this ResponseFour.
        :rtype: str
        """
        return self._error_description

    @error_description.setter
    def error_description(self, error_description):
        """Sets the error_description of this ResponseFour.

        The mobile number provided is associated with more than one DigiLocker accounts. Please login using username.

        :param error_description: The error_description of this ResponseFour.
        :type error_description: str
        """

        self._error_description = error_description
